// Index order must exactly match `class_to_idx` in the fine-tuned checkpoint
// (apps/web/public/models/finetune47_depth3.pt) and therefore the output
// layer of apps/web/public/models/breed_classifier.onnx.
export const BREED_LABELS = [
  { id: "abyssinian", friendly: "Abyssinian", petType: "cat", earStyle: "pointed" },
  { id: "american_bulldog", friendly: "American Bulldog", petType: "dog", earStyle: "floppy" },
  { id: "american_pit_bull_terrier", friendly: "American Pit Bull Terrier", petType: "dog" },
  { id: "american_shorthair", friendly: "American Shorthair", petType: "cat", earStyle: "pointed" },
  { id: "basset_hound", friendly: "Basset Hound", petType: "dog", earStyle: "floppy" },
  { id: "beagle", friendly: "Beagle", petType: "dog", earStyle: "floppy" },
  { id: "bengal", friendly: "Bengal", petType: "cat", earStyle: "pointed" },
  { id: "birman", friendly: "Birman", petType: "cat", earStyle: "pointed" },
  { id: "bombay", friendly: "Bombay", petType: "cat", earStyle: "pointed" },
  { id: "boxer", friendly: "Boxer", petType: "dog", earStyle: "floppy" },
  { id: "british_shorthair", friendly: "British Shorthair", petType: "cat", earStyle: "pointed" },
  { id: "bulldog", friendly: "Bulldog", petType: "dog", earStyle: "floppy" },
  { id: "chihuahua", friendly: "Chihuahua", petType: "dog", earStyle: "pointed" },
  { id: "corgi", friendly: "Corgi", petType: "dog", earStyle: "pointed" },
  { id: "dachshund", friendly: "Dachshund", petType: "dog", earStyle: "floppy" },
  { id: "egyptian_mau", friendly: "Egyptian Mau", petType: "cat", earStyle: "pointed" },
  { id: "english_cocker_spaniel", friendly: "English Cocker Spaniel", petType: "dog", earStyle: "floppy" },
  { id: "english_setter", friendly: "English Setter", petType: "dog", earStyle: "floppy" },
  { id: "german_shepherd", friendly: "German Shepherd", petType: "dog", earStyle: "pointed" },
  { id: "german_shorthaired", friendly: "German Shorthaired Pointer", petType: "dog", earStyle: "floppy" },
  { id: "golden_retriever", friendly: "Golden Retriever", petType: "dog", earStyle: "floppy" },
  { id: "great_pyrenees", friendly: "Great Pyrenees", petType: "dog", earStyle: "floppy" },
  { id: "havanese", friendly: "Havanese", petType: "dog", earStyle: "floppy" },
  { id: "husky", friendly: "Siberian Husky", petType: "dog", earStyle: "pointed" },
  { id: "japanese_chin", friendly: "Japanese Chin", petType: "dog", earStyle: "floppy" },
  { id: "keeshond", friendly: "Keeshond", petType: "dog", earStyle: "pointed" },
  { id: "labrador", friendly: "Labrador Retriever", petType: "dog", earStyle: "floppy" },
  { id: "leonberger", friendly: "Leonberger", petType: "dog", earStyle: "floppy" },
  { id: "maine_coon", friendly: "Maine Coon", petType: "cat", earStyle: "pointed" },
  { id: "miniature_pinscher", friendly: "Miniature Pinscher", petType: "dog", earStyle: "pointed" },
  { id: "mumbai_cat", friendly: "Mumbai Cat", petType: "cat", earStyle: "pointed" },
  { id: "newfoundland", friendly: "Newfoundland", petType: "dog", earStyle: "floppy" },
  { id: "persian_cat", friendly: "Persian", petType: "cat", earStyle: "pointed" },
  { id: "pomeranian", friendly: "Pomeranian", petType: "dog", earStyle: "pointed" },
  { id: "pug", friendly: "Pug", petType: "dog", earStyle: "floppy" },
  { id: "ragdoll_cat", friendly: "Ragdoll", petType: "cat", earStyle: "pointed" },
  { id: "rottwiler", friendly: "Rottweiler", petType: "dog", earStyle: "floppy" },
  { id: "russian_blue", friendly: "Russian Blue", petType: "cat", earStyle: "pointed" },
  { id: "saint_bernard", friendly: "Saint Bernard", petType: "dog", earStyle: "floppy" },
  { id: "samoyed", friendly: "Samoyed", petType: "dog", earStyle: "pointed" },
  { id: "scottish_terrier", friendly: "Scottish Terrier", petType: "dog", earStyle: "pointed" },
  { id: "shiba_inu", friendly: "Shiba Inu", petType: "dog", earStyle: "pointed" },
  { id: "siamese_cat", friendly: "Siamese", petType: "cat", earStyle: "pointed" },
  { id: "sphynx", friendly: "Sphynx", petType: "cat", earStyle: "pointed" },
  { id: "staffordshire_bull_terrier", friendly: "Staffordshire Bull Terrier", petType: "dog" },
  { id: "wheaten_terrier", friendly: "Wheaten Terrier", petType: "dog", earStyle: "floppy" },
  { id: "yorkshire_terrier", friendly: "Yorkshire Terrier", petType: "dog" }
];
