// Maps ImageNet class labels (as returned by @tensorflow-models/mobilenet) to
// friendly pet breed names. ImageNet includes ~120 real dog breeds and 5 cat
// breeds, so matching against these gives genuine breed predictions instead
// of guessing from color/aspect-ratio heuristics.
export const BREED_ENTRIES = [
  { keywords: ["chihuahua"], friendly: "Chihuahua", petType: "dog" },
  { keywords: ["japanese spaniel"], friendly: "Japanese Spaniel", petType: "dog" },
  { keywords: ["maltese"], friendly: "Maltese", petType: "dog" },
  { keywords: ["pekinese", "pekingese", "peke"], friendly: "Pekingese", petType: "dog" },
  { keywords: ["shih-tzu", "shih tzu"], friendly: "Shih Tzu", petType: "dog", earStyle: "floppy" },
  { keywords: ["blenheim spaniel"], friendly: "Blenheim Spaniel", petType: "dog" },
  { keywords: ["papillon"], friendly: "Papillon", petType: "dog", earStyle: "pointed" },
  { keywords: ["toy terrier"], friendly: "Toy Terrier", petType: "dog" },
  { keywords: ["rhodesian ridgeback"], friendly: "Rhodesian Ridgeback", petType: "dog" },
  { keywords: ["afghan hound", "afghan"], friendly: "Afghan Hound", petType: "dog" },
  { keywords: ["basset"], friendly: "Basset Hound", petType: "dog" },
  { keywords: ["beagle"], friendly: "Beagle", petType: "dog" },
  { keywords: ["bloodhound"], friendly: "Bloodhound", petType: "dog" },
  { keywords: ["bluetick"], friendly: "Bluetick Coonhound", petType: "dog" },
  { keywords: ["black-and-tan coonhound"], friendly: "Black and Tan Coonhound", petType: "dog" },
  { keywords: ["walker hound", "walker foxhound"], friendly: "Walker Hound", petType: "dog" },
  { keywords: ["english foxhound"], friendly: "English Foxhound", petType: "dog" },
  { keywords: ["redbone"], friendly: "Redbone Coonhound", petType: "dog" },
  { keywords: ["borzoi"], friendly: "Borzoi", petType: "dog" },
  { keywords: ["irish wolfhound"], friendly: "Irish Wolfhound", petType: "dog" },
  { keywords: ["italian greyhound"], friendly: "Italian Greyhound", petType: "dog" },
  { keywords: ["whippet"], friendly: "Whippet", petType: "dog" },
  { keywords: ["ibizan hound"], friendly: "Ibizan Hound", petType: "dog", earStyle: "pointed" },
  { keywords: ["norwegian elkhound", "elkhound"], friendly: "Norwegian Elkhound", petType: "dog", earStyle: "pointed" },
  { keywords: ["otterhound"], friendly: "Otterhound", petType: "dog" },
  { keywords: ["saluki"], friendly: "Saluki", petType: "dog" },
  { keywords: ["scottish deerhound", "deerhound"], friendly: "Scottish Deerhound", petType: "dog" },
  { keywords: ["weimaraner"], friendly: "Weimaraner", petType: "dog" },
  { keywords: ["staffordshire bullterrier", "staffordshire bull terrier"], friendly: "Staffordshire Bull Terrier", petType: "dog" },
  { keywords: ["american staffordshire terrier", "pit bull terrier"], friendly: "American Staffordshire Terrier", petType: "dog" },
  { keywords: ["bedlington terrier"], friendly: "Bedlington Terrier", petType: "dog" },
  { keywords: ["border terrier"], friendly: "Border Terrier", petType: "dog" },
  { keywords: ["kerry blue terrier"], friendly: "Kerry Blue Terrier", petType: "dog" },
  { keywords: ["irish terrier"], friendly: "Irish Terrier", petType: "dog" },
  { keywords: ["norfolk terrier"], friendly: "Norfolk Terrier", petType: "dog" },
  { keywords: ["norwich terrier"], friendly: "Norwich Terrier", petType: "dog" },
  { keywords: ["yorkshire terrier"], friendly: "Yorkshire Terrier", petType: "dog" },
  { keywords: ["wire-haired fox terrier"], friendly: "Wire Fox Terrier", petType: "dog" },
  { keywords: ["lakeland terrier"], friendly: "Lakeland Terrier", petType: "dog" },
  { keywords: ["sealyham terrier", "sealyham"], friendly: "Sealyham Terrier", petType: "dog" },
  { keywords: ["airedale"], friendly: "Airedale Terrier", petType: "dog" },
  { keywords: ["cairn"], friendly: "Cairn Terrier", petType: "dog" },
  { keywords: ["australian terrier"], friendly: "Australian Terrier", petType: "dog" },
  { keywords: ["dandie dinmont"], friendly: "Dandie Dinmont Terrier", petType: "dog" },
  { keywords: ["boston bull", "boston terrier"], friendly: "Boston Terrier", petType: "dog" },
  { keywords: ["miniature schnauzer"], friendly: "Miniature Schnauzer", petType: "dog" },
  { keywords: ["giant schnauzer"], friendly: "Giant Schnauzer", petType: "dog" },
  { keywords: ["standard schnauzer"], friendly: "Standard Schnauzer", petType: "dog" },
  { keywords: ["scotch terrier", "scottish terrier", "scottie"], friendly: "Scottish Terrier", petType: "dog" },
  { keywords: ["tibetan terrier"], friendly: "Tibetan Terrier", petType: "dog" },
  { keywords: ["silky terrier"], friendly: "Silky Terrier", petType: "dog" },
  { keywords: ["soft-coated wheaten terrier"], friendly: "Wheaten Terrier", petType: "dog" },
  { keywords: ["west highland white terrier"], friendly: "West Highland White Terrier", petType: "dog" },
  { keywords: ["lhasa"], friendly: "Lhasa Apso", petType: "dog" },
  { keywords: ["flat-coated retriever"], friendly: "Flat-Coated Retriever", petType: "dog" },
  { keywords: ["curly-coated retriever"], friendly: "Curly-Coated Retriever", petType: "dog" },
  { keywords: ["golden retriever"], friendly: "Golden Retriever", petType: "dog" },
  { keywords: ["labrador retriever"], friendly: "Labrador Retriever", petType: "dog" },
  { keywords: ["chesapeake bay retriever"], friendly: "Chesapeake Bay Retriever", petType: "dog" },
  { keywords: ["german short-haired pointer"], friendly: "German Shorthaired Pointer", petType: "dog" },
  { keywords: ["vizsla"], friendly: "Vizsla", petType: "dog" },
  { keywords: ["english setter"], friendly: "English Setter", petType: "dog" },
  { keywords: ["irish setter", "red setter"], friendly: "Irish Setter", petType: "dog" },
  { keywords: ["gordon setter"], friendly: "Gordon Setter", petType: "dog" },
  { keywords: ["brittany spaniel"], friendly: "Brittany Spaniel", petType: "dog" },
  { keywords: ["clumber"], friendly: "Clumber Spaniel", petType: "dog" },
  { keywords: ["english springer"], friendly: "English Springer Spaniel", petType: "dog" },
  { keywords: ["welsh springer spaniel"], friendly: "Welsh Springer Spaniel", petType: "dog" },
  { keywords: ["cocker spaniel", "cocker"], friendly: "Cocker Spaniel", petType: "dog" },
  { keywords: ["sussex spaniel"], friendly: "Sussex Spaniel", petType: "dog" },
  { keywords: ["irish water spaniel"], friendly: "Irish Water Spaniel", petType: "dog" },
  { keywords: ["kuvasz"], friendly: "Kuvasz", petType: "dog" },
  { keywords: ["schipperke"], friendly: "Schipperke", petType: "dog", earStyle: "pointed" },
  { keywords: ["groenendael"], friendly: "Belgian Sheepdog", petType: "dog", earStyle: "pointed" },
  { keywords: ["malinois"], friendly: "Belgian Malinois", petType: "dog", earStyle: "pointed" },
  { keywords: ["briard"], friendly: "Briard", petType: "dog" },
  { keywords: ["kelpie"], friendly: "Kelpie", petType: "dog", earStyle: "pointed" },
  { keywords: ["komondor"], friendly: "Komondor", petType: "dog" },
  { keywords: ["old english sheepdog", "bobtail"], friendly: "Old English Sheepdog", petType: "dog" },
  { keywords: ["shetland sheepdog", "shetland"], friendly: "Shetland Sheepdog", petType: "dog", earStyle: "pointed" },
  { keywords: ["collie"], friendly: "Collie", petType: "dog" },
  { keywords: ["border collie"], friendly: "Border Collie", petType: "dog", earStyle: "pointed" },
  { keywords: ["bouvier des flandres"], friendly: "Bouvier des Flandres", petType: "dog" },
  { keywords: ["rottweiler"], friendly: "Rottweiler", petType: "dog" },
  { keywords: ["german shepherd", "alsatian"], friendly: "German Shepherd", petType: "dog", earStyle: "pointed" },
  { keywords: ["doberman"], friendly: "Doberman Pinscher", petType: "dog", earStyle: "pointed" },
  { keywords: ["miniature pinscher"], friendly: "Miniature Pinscher", petType: "dog", earStyle: "pointed" },
  { keywords: ["greater swiss mountain dog"], friendly: "Greater Swiss Mountain Dog", petType: "dog" },
  { keywords: ["bernese mountain dog"], friendly: "Bernese Mountain Dog", petType: "dog" },
  { keywords: ["appenzeller"], friendly: "Appenzeller Sennenhund", petType: "dog" },
  { keywords: ["entlebucher"], friendly: "Entlebucher Mountain Dog", petType: "dog" },
  { keywords: ["boxer"], friendly: "Boxer", petType: "dog" },
  { keywords: ["bull mastiff"], friendly: "Bullmastiff", petType: "dog" },
  { keywords: ["tibetan mastiff"], friendly: "Tibetan Mastiff", petType: "dog" },
  { keywords: ["french bulldog"], friendly: "French Bulldog", petType: "dog", earStyle: "pointed" },
  { keywords: ["great dane"], friendly: "Great Dane", petType: "dog" },
  { keywords: ["saint bernard", "st bernard"], friendly: "Saint Bernard", petType: "dog" },
  { keywords: ["eskimo dog", "husky"], friendly: "Siberian Husky", petType: "dog", earStyle: "pointed" },
  { keywords: ["malamute", "alaskan malamute"], friendly: "Alaskan Malamute", petType: "dog", earStyle: "pointed" },
  { keywords: ["siberian husky"], friendly: "Siberian Husky", petType: "dog", earStyle: "pointed" },
  { keywords: ["affenpinscher"], friendly: "Affenpinscher", petType: "dog" },
  { keywords: ["basenji"], friendly: "Basenji", petType: "dog", earStyle: "pointed" },
  { keywords: ["pug"], friendly: "Pug", petType: "dog" },
  { keywords: ["leonberg"], friendly: "Leonberger", petType: "dog" },
  { keywords: ["newfoundland"], friendly: "Newfoundland", petType: "dog" },
  { keywords: ["great pyrenees"], friendly: "Great Pyrenees", petType: "dog" },
  { keywords: ["samoyed"], friendly: "Samoyed", petType: "dog", earStyle: "pointed" },
  { keywords: ["pomeranian"], friendly: "Pomeranian", petType: "dog", earStyle: "pointed" },
  { keywords: ["chow"], friendly: "Chow Chow", petType: "dog", earStyle: "pointed" },
  { keywords: ["keeshond"], friendly: "Keeshond", petType: "dog", earStyle: "pointed" },
  { keywords: ["brabancon griffon"], friendly: "Brussels Griffon", petType: "dog" },
  { keywords: ["pembroke"], friendly: "Pembroke Welsh Corgi", petType: "dog", earStyle: "pointed" },
  { keywords: ["cardigan"], friendly: "Cardigan Welsh Corgi", petType: "dog", earStyle: "pointed" },
  { keywords: ["toy poodle"], friendly: "Toy Poodle", petType: "dog" },
  { keywords: ["miniature poodle"], friendly: "Miniature Poodle", petType: "dog" },
  { keywords: ["standard poodle"], friendly: "Standard Poodle", petType: "dog" },
  { keywords: ["mexican hairless"], friendly: "Xoloitzcuintli", petType: "dog" },
  { keywords: ["dingo"], friendly: "Dingo", petType: "dog", earStyle: "pointed" },
  { keywords: ["dalmatian"], friendly: "Dalmatian", petType: "dog" },
  { keywords: ["tabby"], friendly: "Tabby Cat", petType: "cat", earStyle: "pointed" },
  { keywords: ["tiger cat"], friendly: "Tiger Cat", petType: "cat", earStyle: "pointed" },
  { keywords: ["persian cat"], friendly: "Persian Cat", petType: "cat", earStyle: "floppy" },
  { keywords: ["siamese"], friendly: "Siamese Cat", petType: "cat", earStyle: "pointed" },
  { keywords: ["egyptian cat"], friendly: "Egyptian Cat", petType: "cat", earStyle: "pointed" }
];

export function matchBreed(predictions = []) {
  for (const prediction of predictions) {
    const phrases = (prediction.className || "")
      .toLowerCase()
      .split(",")
      .map((phrase) => phrase.trim());

    const entry = BREED_ENTRIES.find((candidate) =>
      candidate.keywords.some((keyword) => phrases.some((phrase) => phrase.includes(keyword)))
    );

    if (entry) {
      return { ...entry, confidence: prediction.probability };
    }
  }

  return null;
}
