function capitalizeWord(value) {
  if (!value) {
    return "";
  }
  return value.charAt(0).toUpperCase() + value.slice(1);
}

export function exportQuizResultImage(payload) {
  const canvas = document.createElement("canvas");
  canvas.width = 1080;
  canvas.height = 1080;

  const ctx = canvas.getContext("2d");
  if (!ctx) {
    return;
  }

  ctx.fillStyle = "#fff8f4";
  ctx.fillRect(0, 0, canvas.width, canvas.height);

  ctx.fillStyle = "#ff8ba7";
  ctx.fillRect(60, 60, 960, 180);

  ctx.fillStyle = "#ffffff";
  ctx.font = "bold 54px Poppins, sans-serif";
  ctx.fillText("Purrish&Co. Quiz Result", 90, 165);

  const matchName = payload?.match?.name || "Your Pet Match";
  const summary =
    payload?.summary ||
    "Your personality points to a great companion. See your detailed result in app.";
  const confidence = Math.round((payload?.match?.confidence || 0) * 100);
  const topTraits = (payload?.topTraits || [])
    .slice(0, 3)
    .map((item) => capitalizeWord(item.key))
    .join(" • ");

  ctx.fillStyle = "#333";
  ctx.font = "bold 70px Poppins, sans-serif";
  ctx.fillText(matchName, 90, 360);

  ctx.font = "500 38px Poppins, sans-serif";
  ctx.fillStyle = "#555";
  const summaryLines = [summary.slice(0, 56), summary.slice(56, 112)].filter(Boolean);
  summaryLines.forEach((line, index) => {
    ctx.fillText(line, 90, 440 + index * 48);
  });

  ctx.fillStyle = "#7fd1b9";
  ctx.fillRect(90, 560, 900, 2);

  ctx.fillStyle = "#333";
  ctx.font = "600 42px Poppins, sans-serif";
  ctx.fillText(`Confidence: ${confidence}%`, 90, 660);

  ctx.font = "500 34px Poppins, sans-serif";
  ctx.fillText(`Top Traits: ${topTraits || "Balanced"}`, 90, 730);

  ctx.font = "500 30px Poppins, sans-serif";
  ctx.fillStyle = "#666";
  ctx.fillText("Generated by Purrish&Co. Person-Pet Quiz", 90, 850);

  const link = document.createElement("a");
  link.download = "purrishco-result.png";
  link.href = canvas.toDataURL("image/png");
  link.click();
}
